version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=blog
      - MYSQL_DATABASE=blog

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./blog/django_static:/django_static
      - ./blog/media:/media
    ports:
      - "80:80"
    #  - "443:443"
    depends_on:
      - web

  web:
    build: .
    # command: python manage.py runserver 0:8000
    # ports:
    #   - "8000:8000"
    command: bash -c 'python manage.py collectstatic --noinput && uwsgi --ini uwsgi.ini'
    working_dir: /code/blog
    volumes:
      - .:/code
    expose:
      - "8000"    
    depends_on:
      - mysql
